---
- name: Initialize the cluster
  shell: "kubeadm init --pod-network-cidr={{ ip_range }} >> cluster_initialized.txt"
  args:
    chdir: "{{ global_log_dir }}"
    creates: cluster_initialized.txt

- name: Ensure root user is kubernetes admin
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export KUBECONFIG=/etc/kubernetes/admin.conf
    marker: '# {mark} ANSIBLE MANAGED BLOCK - kubeconfig'
    insertbefore: BOF
    create: yes 

- name: Install Pod network
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt"
  args:
    chdir: "{{ global_log_dir }}"
    creates: pod_network_setup.txt

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"