---

- name: Install Kubernetes binaries
  apt: 
    name: kubectl
    state: present
    update_cache: yes

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --pod-network-cidr {{ ip_range }}
#  vars:
#    log_dir: "{{ global_log_dir }}"

- name: Apply kube-flannel
  command: kubectl apply -f {{ flannel_repo }}

- include: get_create_join_command.yml


