---

- name: Install Kubernetes binaries
  apt: 
    name: kubectl
    state: present
    update_cache: yes

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --pod-network-cidr {{ ip_range }}


- name: Apply kube-flannel
  command: kubectl apply -f {{ flannel_repo }}

# - include: install_httpd.yml
# - include: copy_code.yml

