# Aply nfs into cluster
---

- name: run alpaca-prod and make it public
  hosts: master
  remote_user: root
  tasks:
    - name: kubectl run alpaca-prod
      shell: kubectl run {{ name }} --image={{ image }} --replicas={{ replicas }} --port={{ port }} --labels="{{ labels }}"
      vars:
        name: bandicoot
        port: 8080
        image: gcr.io/kuar-demo/kuard-amd64:2
        replicas: 2
        labels: ver=2,app=bandicoot,env=prod

    - name: kubectl expose alpaca-prod
      shell: kubectl expose deployment {{ name }} --external-ip={{ external_ip }} --port={{ port }} --target-port={{ target_port }}
      vars:
        name: bandicoot
        port: 9090
        target_port: 8080
